SET ANSI_NULLS ON

SET QUOTED_IDENTIFIER ON

CREATE TABLE [dbo].[MODELOS](
	[COD_MODELO] [int] NOT NULL,
	[NOME] [varchar](40) NOT NULL,	
	CONSTRAINT [PK_MODELO] PRIMARY KEY ([COD_MODELO])
)

INSERT INTO [dbo].[MODELOS](COD_MODELO, NOME) VALUES(1, 'OLÁ MUNDO')